// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddUser implements addUser operation.
//
// Add a new user.
//
// POST /user
func (UnimplementedHandler) AddUser(ctx context.Context, req *User) (r *User, _ error) {
	return r, ht.ErrNotImplemented
}

// GetToken implements getToken operation.
//
// Login as user.
//
// POST /auth/login
func (UnimplementedHandler) GetToken(ctx context.Context, req *UsernamePassword) (r *LoginResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserByUsername implements getUserByUsername operation.
//
// Returns a single user.
//
// GET /user/{username}
func (UnimplementedHandler) GetUserByUsername(ctx context.Context, params GetUserByUsernameParams) (r GetUserByUsernameRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUsers implements getUsers operation.
//
// Returns a list of users.
//
// GET /users
func (UnimplementedHandler) GetUsers(ctx context.Context, params GetUsersParams) (r GetUsersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RefreshToken implements refreshToken operation.
//
// Retrieve new token for user.
//
// POST /auth/token
func (UnimplementedHandler) RefreshToken(ctx context.Context, req *Username) (r *Token, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
